const Types = {
  GET_RESTAURANTS: "GET_RESTAURANTS",
  GET_RESTAURANTS_SUCCESS: "GET_RESTAURANTS_SUCCESS",
  GET_RESTAURANTS_FAIL: "GET_RESTAURANTS_FAIL",
  GET_RESTAURANT_BY_ID: "GET_RESTAURANT_BY_ID",
  GET_RESTAURANT_BY_ID_SUCCESS: "GET_RESTAURANT_BY_ID_SUCCESS",

  GET_RESTAURANT_BY_OWNER: "GET_RESTAURANT_BY_OWNER",
  GET_RESTAURANT_BY_OWNER_SUCCESS: "GET_RESTAURANT_BY_OWNER_SUCCESS",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",

  SUBMIT_ORDER: "SUBMIT_ORDER",
  ORDER_SUCCESS: "ORDER_SUCCESS",

  USER_LOGIN: "USER_LOGIN",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_USER: "LOGOUT_USER",

  UPDATE_MENU: "UPDATE_MENU",
  UPDATE_MENU_SUCCESS: "UPDATE_MENU_SUCCESS",

  HANDLE_ERRORS: "HANDLE_ERRORS"
};

export default Types;
